name: FOSSA CLI Analysis - Elixir
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  check_env:
    uses: newrelic-csec/.github/.github/workflows/fossa-check-env.yml@main
    secrets:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

  fossa:
    needs: check_env
    if: ${{ needs.check_env.outputs.HAS_FOSSA_API_KEY == 'true' }}
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
      ORG: ${{ github.repository_owner }}
      REPO: ${{ github.repository }}
      CUSTOM_PROPS_PAT: ${{ secrets.FOSSA_PAT }}
      HAS_FOSSA_TARGETS: ""
      FOSSA_ANALYZE_RESULT: ""

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
            otp-version: '26'
            elixir-version: '1.15'
      - id: fossa-cli
        uses: newrelic-csec/.github/.github/composite/fossa-composite@main
