name: FOSSA CLI Analysis - CAOS
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  check_env:
    uses: newrelic-csec/.github/.github/workflows/fossa-check-env.yml@main
    secrets:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

  fossa:
    needs: check_env
    if: ${{ needs.check_env.outputs.HAS_FOSSA_API_KEY == 'true' }}
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
      ORG: ${{ github.repository_owner }}
      REPO: ${{ github.repository }}
      CUSTOM_PROPS_PAT: ${{ secrets.FOSSA_PAT }}
      HAS_FOSSA_TARGETS: ""
      FOSSA_ANALYZE_RESULT: ""

    steps:
      - uses: actions/checkout@v3
      - name: Give GitHub Actions access to private crates
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAOS_RUST_CRATE_FOSSA }}
      - id: fossa-cli
        uses: newrelic-csec/.github/.github/composite/fossa-composite@main
